#!/bin/bash

# ------------------------------------------------------------------------------
# This tool trawls through /proc looking for existing instances of
# envoy-docker-shim that are running. It then re-runs the command with the
# -reload flag added. This causes the shim to re-sync a new instance of the
# server with the current state. Existing copies of the shim are not disturbed,
# and they will still correctly deregister the container on shutdown.
# ------------------------------------------------------------------------------

ps -ef | grep "envoy-docker-shi[m]" | grep -v dockerd | awk '{for(i=8;i<=NF;++i)printf("%s ", $i); print ""}' | (
	while read -r line; do
		line="$line -reload"
		echo "+ $line"
		eval "$line"
	done
)
