// Code generated by protoc-gen-go.
// source: shimrpc.proto
// DO NOT EDIT!

/*
Package shimrpc is a generated protocol buffer package.

It is generated from these files:
	shimrpc.proto

It has these top-level messages:
	RegistrarRequest
	RegistrarReply
*/
package shimrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegistrarRequest_Action int32

const (
	RegistrarRequest_REGISTER   RegistrarRequest_Action = 0
	RegistrarRequest_DEREGISTER RegistrarRequest_Action = 1
)

var RegistrarRequest_Action_name = map[int32]string{
	0: "REGISTER",
	1: "DEREGISTER",
}
var RegistrarRequest_Action_value = map[string]int32{
	"REGISTER":   0,
	"DEREGISTER": 1,
}

func (x RegistrarRequest_Action) String() string {
	return proto.EnumName(RegistrarRequest_Action_name, int32(x))
}
func (RegistrarRequest_Action) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// The requested listener and cluster member
type RegistrarRequest struct {
	FrontendAddr string                  `protobuf:"bytes,1,opt,name=frontend_addr,json=frontendAddr" json:"frontend_addr,omitempty"`
	FrontendPort int32                   `protobuf:"varint,2,opt,name=frontend_port,json=frontendPort" json:"frontend_port,omitempty"`
	BackendAddr  string                  `protobuf:"bytes,3,opt,name=backend_addr,json=backendAddr" json:"backend_addr,omitempty"`
	BackendPort  int32                   `protobuf:"varint,4,opt,name=backend_port,json=backendPort" json:"backend_port,omitempty"`
	Action       RegistrarRequest_Action `protobuf:"varint,5,opt,name=action,enum=shimrpc.RegistrarRequest_Action" json:"action,omitempty"`
}

func (m *RegistrarRequest) Reset()                    { *m = RegistrarRequest{} }
func (m *RegistrarRequest) String() string            { return proto.CompactTextString(m) }
func (*RegistrarRequest) ProtoMessage()               {}
func (*RegistrarRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RegistrarRequest) GetFrontendAddr() string {
	if m != nil {
		return m.FrontendAddr
	}
	return ""
}

func (m *RegistrarRequest) GetFrontendPort() int32 {
	if m != nil {
		return m.FrontendPort
	}
	return 0
}

func (m *RegistrarRequest) GetBackendAddr() string {
	if m != nil {
		return m.BackendAddr
	}
	return ""
}

func (m *RegistrarRequest) GetBackendPort() int32 {
	if m != nil {
		return m.BackendPort
	}
	return 0
}

func (m *RegistrarRequest) GetAction() RegistrarRequest_Action {
	if m != nil {
		return m.Action
	}
	return RegistrarRequest_REGISTER
}

// The response message containing the status
type RegistrarReply struct {
	StatusCode int32 `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
}

func (m *RegistrarReply) Reset()                    { *m = RegistrarReply{} }
func (m *RegistrarReply) String() string            { return proto.CompactTextString(m) }
func (*RegistrarReply) ProtoMessage()               {}
func (*RegistrarReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RegistrarReply) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func init() {
	proto.RegisterType((*RegistrarRequest)(nil), "shimrpc.RegistrarRequest")
	proto.RegisterType((*RegistrarReply)(nil), "shimrpc.RegistrarReply")
	proto.RegisterEnum("shimrpc.RegistrarRequest_Action", RegistrarRequest_Action_name, RegistrarRequest_Action_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Registrar service

type RegistrarClient interface {
	Register(ctx context.Context, in *RegistrarRequest, opts ...grpc.CallOption) (*RegistrarReply, error)
}

type registrarClient struct {
	cc *grpc.ClientConn
}

func NewRegistrarClient(cc *grpc.ClientConn) RegistrarClient {
	return &registrarClient{cc}
}

func (c *registrarClient) Register(ctx context.Context, in *RegistrarRequest, opts ...grpc.CallOption) (*RegistrarReply, error) {
	out := new(RegistrarReply)
	err := grpc.Invoke(ctx, "/shimrpc.Registrar/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Registrar service

type RegistrarServer interface {
	Register(context.Context, *RegistrarRequest) (*RegistrarReply, error)
}

func RegisterRegistrarServer(s *grpc.Server, srv RegistrarServer) {
	s.RegisterService(&_Registrar_serviceDesc, srv)
}

func _Registrar_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrarServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shimrpc.Registrar/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrarServer).Register(ctx, req.(*RegistrarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Registrar_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shimrpc.Registrar",
	HandlerType: (*RegistrarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Registrar_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shimrpc.proto",
}

func init() { proto.RegisterFile("shimrpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x91, 0xcf, 0x4f, 0xc2, 0x30,
	0x14, 0xc7, 0x29, 0x0a, 0xc2, 0x63, 0x10, 0xd2, 0x8b, 0xe0, 0xc5, 0x39, 0x13, 0x43, 0x62, 0xb2,
	0x44, 0xbc, 0x78, 0x14, 0x74, 0x31, 0x1e, 0x4c, 0x96, 0xe2, 0x9d, 0x8c, 0xb6, 0xc2, 0x22, 0xdb,
	0xab, 0x5d, 0x31, 0xd9, 0xdd, 0x3f, 0xdc, 0xd8, 0xfd, 0x10, 0x8d, 0x1e, 0xbf, 0xdf, 0x7e, 0xfa,
	0xc9, 0x6b, 0x1f, 0xf4, 0xb3, 0x4d, 0x9c, 0x68, 0xc5, 0x7d, 0xa5, 0xd1, 0x20, 0x3d, 0x2a, 0xa3,
	0xf7, 0xd1, 0x84, 0x21, 0x93, 0xeb, 0x38, 0x33, 0x3a, 0xd2, 0x4c, 0xbe, 0xed, 0x64, 0x66, 0xe8,
	0x39, 0xf4, 0x5f, 0x34, 0xa6, 0x46, 0xa6, 0x62, 0x19, 0x09, 0xa1, 0x47, 0xc4, 0x25, 0x93, 0x2e,
	0x73, 0xaa, 0x72, 0x26, 0x84, 0xfe, 0x01, 0x29, 0xd4, 0x66, 0xd4, 0x74, 0xc9, 0xa4, 0xf5, 0x0d,
	0x85, 0xa8, 0x0d, 0x3d, 0x03, 0x67, 0x15, 0xf1, 0xd7, 0x5a, 0x74, 0x60, 0x45, 0xbd, 0xb2, 0xb3,
	0x9e, 0x3d, 0xc4, 0x6a, 0x0e, 0xad, 0xa6, 0x42, 0xac, 0xe5, 0x06, 0xda, 0x11, 0x37, 0x31, 0xa6,
	0xa3, 0x96, 0x4b, 0x26, 0x83, 0xa9, 0xeb, 0x57, 0xaf, 0xf9, 0x3d, 0xba, 0x3f, 0xb3, 0x1c, 0x2b,
	0x79, 0xef, 0x02, 0xda, 0x45, 0x43, 0x1d, 0xe8, 0xb0, 0xe0, 0xe1, 0x71, 0xf1, 0x1c, 0xb0, 0x61,
	0x83, 0x0e, 0x00, 0xee, 0x83, 0x3a, 0x13, 0xef, 0x0a, 0x06, 0x7b, 0x2a, 0xb5, 0xcd, 0xe9, 0x29,
	0xf4, 0x32, 0x13, 0x99, 0x5d, 0xb6, 0xe4, 0x28, 0xa4, 0xfd, 0x81, 0x16, 0x83, 0xa2, 0xba, 0x43,
	0x21, 0xa7, 0x4f, 0xd0, 0xad, 0xaf, 0xd0, 0x5b, 0xe8, 0x14, 0x41, 0x6a, 0x3a, 0xfe, 0x77, 0xba,
	0x93, 0xe3, 0xbf, 0x8e, 0xd4, 0x36, 0xf7, 0x1a, 0xf3, 0x4b, 0x18, 0x73, 0x4c, 0xfc, 0x35, 0xa6,
	0xb1, 0xd1, 0xe8, 0xcb, 0xf4, 0x1d, 0xf3, 0x8a, 0x9e, 0x3b, 0x8b, 0x4d, 0x9c, 0x30, 0xc5, 0xc3,
	0xaf, 0xe5, 0x85, 0x64, 0xd5, 0xb6, 0x5b, 0xbc, 0xfe, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x3e, 0xa7,
	0x94, 0x60, 0xd6, 0x01, 0x00, 0x00,
}
